# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170629_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prioridades',
            new_name='Prioridad',
        ),
    ]
